<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BedroomsSeeder extends Seeder
{
    public function run()
    {
        $bedrooms =  [
            [
                'name' => 'Habitación 1',
                'description' => 'Descripción de la habitación 1',
                'square_meters' => 25,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 2',
                'description' => 'Descripción de la habitación 2',
                'square_meters' => 30,
                'num_bathrooms' => 1,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => false,
                'wifi' => true,
                'tv' => true,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 3',
                'description' => 'Descripción de la habitación 3',
                'square_meters' => 22,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 4',
                'description' => 'Descripción de la habitación 4',
                'square_meters' => 35,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 5',
                'description' => 'Descripción de la habitación 5',
                'square_meters' => 28,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 6',
                'description' => 'Descripción de la habitación 6',
                'square_meters' => 40,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 7',
                'description' => 'Descripción de la habitación 7',
                'square_meters' => 18,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 8',
                'description' => 'Descripción de la habitación 8',
                'square_meters' => 24,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => false,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 9',
                'description' => 'Descripción de la habitación 9',
                'square_meters' => 32,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 10',
                'description' => 'Descripción de la habitación 10',
                'square_meters' => 29,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 11',
                'description' => 'Descripción de la habitación 11',
                'square_meters' => 25,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 12',
                'description' => 'Descripción de la habitación 12',
                'square_meters' => 30,
                'num_bathrooms' => 1,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => false,
                'wifi' => true,
                'tv' => true,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 13',
                'description' => 'Descripción de la habitación 13',
                'square_meters' => 22,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 14',
                'description' => 'Descripción de la habitación 14',
                'square_meters' => 35,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 15',
                'description' => 'Descripción de la habitación 15',
                'square_meters' => 28,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 16',
                'description' => 'Descripción de la habitación 16',
                'square_meters' => 40,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 17',
                'description' => 'Descripción de la habitación 17',
                'square_meters' => 18,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 18',
                'description' => 'Descripción de la habitación 8',
                'square_meters' => 24,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => false,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 19',
                'description' => 'Descripción de la habitación 19',
                'square_meters' => 32,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 20',
                'description' => 'Descripción de la habitación 20',
                'square_meters' => 29,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 21',
                'description' => 'Descripción de la habitación 21',
                'square_meters' => 25,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 22',
                'description' => 'Descripción de la habitación 2',
                'square_meters' => 30,
                'num_bathrooms' => 1,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => false,
                'wifi' => true,
                'tv' => true,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 23',
                'description' => 'Descripción de la habitación 23',
                'square_meters' => 22,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 24',
                'description' => 'Descripción de la habitación 24',
                'square_meters' => 35,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 25',
                'description' => 'Descripción de la habitación 25',
                'square_meters' => 28,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 26',
                'description' => 'Descripción de la habitación 26',
                'square_meters' => 40,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => false,
                'heating' => true,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 27',
                'description' => 'Descripción de la habitación 27',
                'square_meters' => 18,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 28',
                'description' => 'Descripción de la habitación 28',
                'square_meters' => 24,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => false,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 29',
                'description' => 'Descripción de la habitación 29',
                'square_meters' => 32,
                'num_bathrooms' => 2,
                'chimney' => true,
                'terrace' => false,
                'available_smoke_detector' => true,
                'wifi' => true,
                'tv' => true,
                'heating' => false,
                'parking_lot' => true,
                'adapted_use' => false,
                'bedrooms_type_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Habitación 30',
                'description' => 'Descripción de la habitación 30',
                'square_meters' => 29,
                'num_bathrooms' => 1,
                'chimney' => false,
                'terrace' => true,
                'available_smoke_detector' => true,
                'wifi' => false,
                'tv' => true,
                'heating' => true,
                'parking_lot' => false,
                'adapted_use' => true,
                'bedrooms_type_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('bedrooms')->insertBatch($bedrooms);
    }
}
